services:
  # 1. Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: intuitive-db
    environment:
      POSTGRES_USER: user_intuitive
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: intuitive_care
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  # 2. Backend (FastAPI)
  backend:
    build: .
    container_name: intuitive-backend
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://user_intuitive:password123@db:5432/intuitive_care
      - DB_HOST=db # ESSENCIAL para o pipeline funcionar via docker compose exec
    depends_on:
      - db
    volumes:
      - .:/app # Mapeia a raiz para acessar a pasta etl/ e data/

  # 3. Frontend (Vue.js)
  frontend:
    build: ./frontend
    container_name: intuitive-frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  postgres_data:
